export interface Post {
    id?: number,
    title?: string,
    desc?: string,
    created_at?: Date | string,
    updated_at?: Date | string,
    galleries?: any[],
    price?: number,
    address?: string,
    phone?: string,
    email?: string,
    user_id?:number,
    username?:string,
    status?:string,
    type?:string,
    imgCount?:number,
    main_img?:string,
    city_id?: number,
    cityNameAR?:string,
    cityNameEN?:string
}